spring:
  application:
    name: training-project

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://mysql-container:3306/testdb?allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true
    username: root
    password: password
    hikari:
      maximum-pool-size: 10   # максимальное количество соединений в пуле
      minimum-idle: 2         # минимальное количество соединений в режиме простоя
      idle-timeout: 30000      # время простоя перед закрытием соединения (мс)
      connection-timeout: 20000 # время ожидания соединения (мс)
      initialization-fail-timeout: 0

  jpa:
    open-in-view: false  # закрывать EntityManager после запроса (оптимизация)
    show-sql: true # пишем в лог все sql, которые выполняются
    hibernate:
      ddl-auto: create # автоматически создаем таблицы и связи между ними
    properties:
       hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27817/app

logging:
  level:
    # если нужны более подробные логи - раскоментируй
    #root: DEBUG
    edu.serjmaks.training_project: INFO
    #edu.serjmaks.training_project: DEBUG
    #org.springframework: DEBUG
    #org.hibernate: DEBUG

# actuator
management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
